Feature/rr test development
temoto-telerobotics/temoto_resource_registrar pull request #1
Opened 2021-01-09 12:20 UTC by Akustav

2021-01-13 12:01 UTC, RValner requested changes
High level comments:
- Renaming and merging:
  * rename `rr_message_registry` to `rr_catalog`
  * merge `rr_registry` under `rr_base`, because they are supposed to be the same thing
- RrClientRepository and RrServerReporitory seem to share/duplicate code. What I propose is: 
  * define a common templated class called `template<T> class RrServerClientUtil`
  * define `class RrClientRepository : public RrRepository<RrClientRepositoryEntry>`
  * define `class RrServerRepository : public RrRepository<RrServerRepositoryEntry>`
  * move all these util classes under rr_server_client_util.h/.cpp
  so that the common functionalities are defined in `RrServerClientUtil` and the specific functionalities are in the according derived classes.
- There is no point in having a global status callback registration method, as there is in the "RrRegistry" class. Yes, that's how it used to be but it makes more sense that each "RrClient" object has a status callback which is provided while creating the client
- Each client status callback should be part of the client object. Atm the clients and callbacks are in separate maps
- It's currently hard to grasp the motivation for some classes, such as "Identifiable" - so please do add short doxygen styled comments (via doxygen plugin in VS code) in front of the class declarations
- RrClientBase does not have a pointer to the RrCatalog, which seems to imply that the catalog cannot maintain resource dependencies
- QueryRequest and QueryResponse classes should prolly be templated, atm they hold a "std::string", but the requests and responses are unique per server. This is more of a loose subject at the moment, since there is the matter of RR Catalog serialization. TBD.

2021-01-13 12:01 UTC, RValner commented on rr_core/include/temoto_resource_registrar/rr_base.h
> +#include "rr_resource.h"
Seems to be unused and also conceptually it's not going to be used.

2021-01-13 12:01 UTC, RValner commented on rr_core/include/temoto_resource_registrar/rr_base.h
>  #include "rr_registry.h"
Are "rr_registry" and "rr_message_registry" functionally different? Also rename "registry" to "catalog"

2021-01-13 12:01 UTC, RValner commented on rr_core/include/temoto_resource_registrar/rr_client_base.h
> +    //RrRegistryPtr rr_registry_;
Conceptually all client and server queries should meet at the RR Catalog, hence there should be a pointer to a RR Catalog

2021-01-13 12:01 UTC, RValner commented on rr_core/include/temoto_resource_registrar/rr_identifiable.h
> +  class Identifiable
What is the purpose of this class?

2021-01-13 12:01 UTC, RValner commented on rr_core/include/temoto_resource_registrar/rr_message_registry.h
> +  class RrMessageRegistry
This class should hold both the queries of the clients and servers AND the dependencies between server and client queries

2021-01-13 12:01 UTC, RValner commented on rr_core/include/temoto_resource_registrar/rr_registry.h
> +    void registerStatusCallback(std::function<void(RrClientBase)> rrStatusCallback);
There is no point in having a global status callback registration method. Yes, that's how it used to be but it makes more sense that each "RrClient" object has a status callback which is provided while creating the client

2021-01-17 13:49 UTC, Akustav commented on rr_core/include/temoto_resource_registrar/rr_identifiable.h
> +  class Identifiable
This is a interface that describes a method that should be used when storing these in maps. It is their unique identifier

2021-01-17 13:55 UTC, Akustav commented on rr_core/include/temoto_resource_registrar/rr_base.h
>  #include "rr_registry.h"
Conceptually they are the same, one stores clients and servers, the other stores messages. Both can be merged into one, if need be

2021-01-17 15:33 UTC, Akustav commented on rr_core/include/temoto_resource_registrar/rr_message_registry.h
> +  class RrMessageRegistry
Dependencies meaning that if a resource is dependent on multiple subresources this relationship is marked down in a map of vectors, for example?

2021-06-05 13:29 UTC, closed without merging